[package]
name = "zythdotdev/flux"
description = "A simple reactive UI framework for Roblox"
version = "1.0.0"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
private = true

[dependencies]
Bag = "zythdotdev/bag@2.0.0"
Value = "zythdotdev/value@2.1.0"